version: '3.7'

services:
  simple-react-app-dockerized:
    image: simple-react-app-dockerized
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
