version: '3.7'

services:
  simple-react-app-dockerized:
    image: simple-react-app-dockerized
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js
